- hosts: nfs
  become: true
  vars:
    share_path: /mnt/nfsroot
  tasks:
    - name: install nfs
      yum: 
        name: nfs-utils
        state: latest
    - name: start and enable nfs-server
      service:
        name: nfs-server
        state: started
        enabled: yes
    - name: configure exports
      template:
        src: /home/ansible/exports.j2
        dest: /etc/exports
      notify: update nfs
  handlers:
    - name: update nfs
      command:
        cmd: exportfs -a

- hosts: remote
  become: yes
  vars:
    nfs_ip: "{{ hostvars['nfs']['ansible_default_ipv4']['address'] }}"
    nfs_hostname: "{{ hostvars['nfs']['ansible_hostname'] }}"
  vars_files:
    - /home/ansible/user-list.txt
  tasks:
    - name: configure host file
      template:
        src: /home/ansible/etc.hosts.j2
        dest: /etc/hosts
    - name: get file status
      stat: 
        path: /opt/user-agreement.txt
      register: filestat
    - name: debug info
      debug: 
        var: filestat
    - name: create users
      user:
        name: "{{ item }}"
      when: filestat.stat.exists
      loop: "{{ users }}"
