---
# tasks file for roles/webservers
- name: Upload application file        
  copy:
    src: ../files/index.php
    dest: "{{ path_to_app }}"
    mode: 075
- name: Info about node
  copy:
    dest: "{{ path_to_app }}/info.php"
    content: "<h1> {{ ansible_hostname }} </h1>"   
- name: Listar informações
  command: "ls -la {{ path_to_app }}"    
  register: path_content
- name: Exibir informações com o módulo debug
  debug:
    msg: "{{ path_content }}" 
- name: Configure php.ini file
  lineinfile: 
    path: /etc/php.ini
    regexp: ^short_open_tag
    line: 'short_open_tag=On'   
  notify: restart apache